FROM alpine:3.14

RUN apk add bash

RUN apk update \
  && apk upgrade \
  && apk add ca-certificates \
  && update-ca-certificates \
  && apk add --update coreutils \
  && rm -rf /var/cache/apk/*

RUN apk --no-cache add openjdk17 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community \
  && rm -rf /var/cache/apk/*

ENV JAVA_HOME=/usr/lib/jvm/default-jvm

WORKDIR /app/

COPY target/drones-api-0.0.1-SNAPSHOT.jar /app/drones-api.jar

EXPOSE 8080

CMD ["java", "-jar", "/app/drones-api.jar"]